### ISSUE TITLE
**path**: team/{team_id}/categories  

### ISSUE THREAD

**Issue by anmolg** [PayUppApp/PayUpp-AWS#83]
Should be returning:
id, category_id, price

**Comment by anmolg** [comment]
rename path to team/{team_id}/category

**Comment by shreyansjain** [comment]
so, it'll return `id, category_id, category_description, price` 
reason for calling it categories instead of category is because it is list of categories for a given team. Category sounds singular

**Comment by anmolg** [comment]
but the path should be consistent I think. We will hvae a separate path for post and a separte path for get

**Comment by anmolg** [comment]
and code table is being maintained on client side so description is redundant

**Comment by shreyansjain** [comment]
You shouldn't be maintaining code table for categories since it is different for each team.

**Comment by shreyansjain** [comment]
sure, i'll then move to /category GET

**Comment by shreyansjain** [comment]
Shall I return
```
{
"category_id" : "x",
"category_description" : "xx"
}
```
OR
```
category : {
    id : x,
    description : xxx
}
```

**Comment by anmolg** [comment]
model approach.

But, the category description associated with id is being maintained right? Each team can only have a pre-defined set of categories?

**Comment by shreyansjain** [comment]
yes, we do maintain id, description for a category. 

Confused now, can admin add more categories? I think, we said, we'll do it for this version?

**Comment by shreyansjain** [comment]
@anmolg can you confirm if i can do the following:
- use model for category id and description
- change path from `/categories` to `/category`

**Comment by anmolg** [comment]
So for GET:
we should be receiving id (db primary key), category_id (code_category fk), price

Model approach is not necessary because client device maintains code_category on device. So we can find description through a match.
